-- Phase 5: Database Schema Extensions
-- New tables for certificates, discussions, live sessions, payments, gamification, and versioning

-- ================================================
-- CERTIFICATES TABLE
-- ================================================
CREATE TABLE EDUX.CERTIFICATES (
    CERT_ID VARCHAR2(50) PRIMARY KEY,
    U_ID NUMBER NOT NULL,
    C_ID NUMBER NOT NULL,
    ISSUED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERIFICATION_URL VARCHAR2(500),
    TEMPLATE VARCHAR2(50) DEFAULT 'STANDARD',
    CONSTRAINT FK_CERT_USER FOREIGN KEY (U_ID) REFERENCES EDUX.USERS(U_ID),
    CONSTRAINT FK_CERT_COURSE FOREIGN KEY (C_ID) REFERENCES EDUX.COURSE(C_ID)
);

CREATE INDEX IDX_CERT_USER ON EDUX.CERTIFICATES(U_ID);
CREATE INDEX IDX_CERT_COURSE ON EDUX.CERTIFICATES(C_ID);

-- ================================================
-- DISCUSSIONS TABLE
-- ================================================
CREATE TABLE EDUX.DISCUSSIONS (
    THREAD_ID VARCHAR2(50) PRIMARY KEY,
    C_ID NUMBER NOT NULL,
    U_ID NUMBER NOT NULL,
    TITLE VARCHAR2(500) NOT NULL,
    CONTENT CLOB,
    IS_PINNED NUMBER(1) DEFAULT 0,
    IS_LOCKED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_DISC_COURSE FOREIGN KEY (C_ID) REFERENCES EDUX.COURSE(C_ID),
    CONSTRAINT FK_DISC_USER FOREIGN KEY (U_ID) REFERENCES EDUX.USERS(U_ID)
);

CREATE TABLE EDUX.DISCUSSION_REPLIES (
    REPLY_ID VARCHAR2(50) PRIMARY KEY,
    THREAD_ID VARCHAR2(50) NOT NULL,
    U_ID NUMBER NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_REPLY_THREAD FOREIGN KEY (THREAD_ID) REFERENCES EDUX.DISCUSSIONS(THREAD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REPLY_USER FOREIGN KEY (U_ID) REFERENCES EDUX.USERS(U_ID)
);

CREATE INDEX IDX_DISC_COURSE ON EDUX.DISCUSSIONS(C_ID);
CREATE INDEX IDX_DISC_USER ON EDUX.DISCUSSIONS(U_ID);
CREATE INDEX IDX_REPLY_THREAD ON EDUX.DISCUSSION_REPLIES(THREAD_ID);

-- ================================================
-- LIVE SESSIONS TABLES
-- ================================================
CREATE TABLE EDUX.LIVE_SESSIONS (
    SESSION_ID VARCHAR2(100) PRIMARY KEY,
    C_ID NUMBER NOT NULL,
    INSTRUCTOR_ID NUMBER NOT NULL,
    TITLE VARCHAR2(500) NOT NULL,
    DESCRIPTION CLOB,
    TYPE VARCHAR2(50) DEFAULT 'lecture',
    ROOM_NAME VARCHAR2(100),
    PASSWORD VARCHAR2(50),
    SCHEDULED_START TIMESTAMP NOT NULL,
    SCHEDULED_END TIMESTAMP,
    DURATION NUMBER DEFAULT 60,
    MAX_PARTICIPANTS NUMBER DEFAULT 100,
    STATUS VARCHAR2(20) DEFAULT 'scheduled',
    STARTED_AT TIMESTAMP,
    ENDED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SESSION_COURSE FOREIGN KEY (C_ID) REFERENCES EDUX.COURSE(C_ID),
    CONSTRAINT FK_SESSION_INSTRUCTOR FOREIGN KEY (INSTRUCTOR_ID) REFERENCES EDUX.INSTRUCTOR(I_ID)
);

CREATE TABLE EDUX.SESSION_PARTICIPANTS (
    SESSION_ID VARCHAR2(100) NOT NULL,
    USER_ID NUMBER NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'participant',
    JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LEFT_AT TIMESTAMP,
    PRIMARY KEY (SESSION_ID, USER_ID),
    CONSTRAINT FK_PARTICIPANT_SESSION FOREIGN KEY (SESSION_ID) REFERENCES EDUX.LIVE_SESSIONS(SESSION_ID),
    CONSTRAINT FK_PARTICIPANT_USER FOREIGN KEY (USER_ID) REFERENCES EDUX.USERS(U_ID)
);

CREATE INDEX IDX_SESSION_COURSE ON EDUX.LIVE_SESSIONS(C_ID);
CREATE INDEX IDX_SESSION_INSTRUCTOR ON EDUX.LIVE_SESSIONS(INSTRUCTOR_ID);
CREATE INDEX IDX_SESSION_STATUS ON EDUX.LIVE_SESSIONS(STATUS);

-- ================================================
-- PAYMENTS TABLE
-- ================================================
CREATE TABLE EDUX.PAYMENTS (
    PAYMENT_ID VARCHAR2(50) PRIMARY KEY,
    U_ID NUMBER NOT NULL,
    C_ID NUMBER NOT NULL,
    AMOUNT NUMBER(10,2) NOT NULL,
    CURRENCY VARCHAR2(3) DEFAULT 'USD',
    STATUS VARCHAR2(20) DEFAULT 'pending',
    STRIPE_SESSION_ID VARCHAR2(200),
    COUPON_CODE VARCHAR2(50),
    REFUND_REASON VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    REFUNDED_AT TIMESTAMP,
    CONSTRAINT FK_PAYMENT_USER FOREIGN KEY (U_ID) REFERENCES EDUX.USERS(U_ID),
    CONSTRAINT FK_PAYMENT_COURSE FOREIGN KEY (C_ID) REFERENCES EDUX.COURSE(C_ID)
);

CREATE INDEX IDX_PAYMENT_USER ON EDUX.PAYMENTS(U_ID);
CREATE INDEX IDX_PAYMENT_COURSE ON EDUX.PAYMENTS(C_ID);
CREATE INDEX IDX_PAYMENT_STATUS ON EDUX.PAYMENTS(STATUS);
CREATE INDEX IDX_PAYMENT_STRIPE ON EDUX.PAYMENTS(STRIPE_SESSION_ID);

-- ================================================
-- GAMIFICATION TABLES
-- ================================================
CREATE TABLE EDUX.USER_XP (
    XP_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    U_ID NUMBER NOT NULL,
    XP_AMOUNT NUMBER NOT NULL,
    ACTION VARCHAR2(100),
    C_ID NUMBER,
    EARNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_XP_USER FOREIGN KEY (U_ID) REFERENCES EDUX.USERS(U_ID),
    CONSTRAINT FK_XP_COURSE FOREIGN KEY (C_ID) REFERENCES EDUX.COURSE(C_ID)
);

CREATE TABLE EDUX.USER_BADGES (
    U_ID NUMBER NOT NULL,
    BADGE_ID VARCHAR2(50) NOT NULL,
    EARNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (U_ID, BADGE_ID),
    CONSTRAINT FK_BADGE_USER FOREIGN KEY (U_ID) REFERENCES EDUX.USERS(U_ID)
);

CREATE TABLE EDUX.USER_ACTIVITY (
    ACTIVITY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    U_ID NUMBER NOT NULL,
    ACTIVITY_TYPE VARCHAR2(50),
    ACTIVITY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACTIVITY_USER FOREIGN KEY (U_ID) REFERENCES EDUX.USERS(U_ID)
);

CREATE TABLE EDUX.USER_STREAKS (
    U_ID NUMBER PRIMARY KEY,
    CURRENT_STREAK NUMBER DEFAULT 0,
    LONGEST_STREAK NUMBER DEFAULT 0,
    LAST_ACTIVITY_DATE DATE,
    CONSTRAINT FK_STREAK_USER FOREIGN KEY (U_ID) REFERENCES EDUX.USERS(U_ID)
);

CREATE INDEX IDX_XP_USER ON EDUX.USER_XP(U_ID);
CREATE INDEX IDX_XP_ACTION ON EDUX.USER_XP(ACTION);
CREATE INDEX IDX_ACTIVITY_USER ON EDUX.USER_ACTIVITY(U_ID);
CREATE INDEX IDX_ACTIVITY_DATE ON EDUX.USER_ACTIVITY(ACTIVITY_DATE);

-- ================================================
-- CONTENT VERSIONING TABLE
-- ================================================
CREATE TABLE EDUX.CONTENT_VERSIONS (
    VERSION_ID VARCHAR2(100) PRIMARY KEY,
    CONTENT_TYPE VARCHAR2(50) NOT NULL,
    CONTENT_ID VARCHAR2(50) NOT NULL,
    COURSE_ID NUMBER,
    ACTION VARCHAR2(20) NOT NULL,
    USER_ID NUMBER,
    PREVIOUS_DATA CLOB,
    NEW_DATA CLOB,
    MESSAGE VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_VERSION_USER FOREIGN KEY (USER_ID) REFERENCES EDUX.USERS(U_ID),
    CONSTRAINT FK_VERSION_COURSE FOREIGN KEY (COURSE_ID) REFERENCES EDUX.COURSE(C_ID)
);

CREATE INDEX IDX_VERSION_CONTENT ON EDUX.CONTENT_VERSIONS(CONTENT_TYPE, CONTENT_ID);
CREATE INDEX IDX_VERSION_COURSE ON EDUX.CONTENT_VERSIONS(COURSE_ID);
CREATE INDEX IDX_VERSION_DATE ON EDUX.CONTENT_VERSIONS(CREATED_AT);

-- ================================================
-- ADD COLUMNS TO EXISTING TABLES
-- ================================================

-- Add COMPLETED and PROGRESS columns to ENROLLMENT
ALTER TABLE EDUX.ENROLLMENT ADD (
    COMPLETED NUMBER(1) DEFAULT 0,
    PROGRESS NUMBER DEFAULT 0,
    COMPLETED_AT TIMESTAMP
);

-- Add PRICE column to COURSE if not exists
ALTER TABLE EDUX.COURSE ADD (
    PRICE NUMBER(10,2) DEFAULT 0
);

-- ================================================
-- VIEWS FOR ANALYTICS
-- ================================================

-- Leaderboard View
CREATE OR REPLACE VIEW EDUX.V_LEADERBOARD AS
SELECT 
    u.U_ID,
    u.NAME,
    NVL(SUM(x.XP_AMOUNT), 0) as TOTAL_XP,
    (SELECT COUNT(*) FROM EDUX.USER_BADGES b WHERE b.U_ID = u.U_ID) as BADGE_COUNT,
    RANK() OVER (ORDER BY NVL(SUM(x.XP_AMOUNT), 0) DESC) as RANK
FROM EDUX.USERS u
LEFT JOIN EDUX.USER_XP x ON u.U_ID = x.U_ID
GROUP BY u.U_ID, u.NAME;

-- Instructor Analytics View
CREATE OR REPLACE VIEW EDUX.V_INSTRUCTOR_STATS AS
SELECT 
    i.I_ID,
    i.NAME as INSTRUCTOR_NAME,
    COUNT(DISTINCT c.C_ID) as TOTAL_COURSES,
    COUNT(DISTINCT e.U_ID) as TOTAL_STUDENTS,
    NVL(AVG(r.RATING), 0) as AVG_RATING,
    COUNT(DISTINCT r.R_ID) as TOTAL_REVIEWS,
    NVL(SUM(p.AMOUNT), 0) as TOTAL_REVENUE
FROM EDUX.INSTRUCTOR i
LEFT JOIN EDUX.COURSE c ON i.I_ID = c.I_ID
LEFT JOIN EDUX.ENROLLMENT e ON c.C_ID = e.C_ID
LEFT JOIN EDUX.COURSE_RATING r ON c.C_ID = r.C_ID
LEFT JOIN EDUX.PAYMENTS p ON c.C_ID = p.C_ID AND p.STATUS = 'completed'
GROUP BY i.I_ID, i.NAME;

-- Course Performance View
CREATE OR REPLACE VIEW EDUX.V_COURSE_PERFORMANCE AS
SELECT 
    c.C_ID,
    c.NAME as COURSE_NAME,
    c.I_ID as INSTRUCTOR_ID,
    COUNT(DISTINCT e.U_ID) as ENROLLMENT_COUNT,
    NVL(AVG(r.RATING), 0) as AVG_RATING,
    COUNT(CASE WHEN e.COMPLETED = 1 THEN 1 END) as COMPLETIONS,
    NVL(AVG(e.PROGRESS), 0) as AVG_PROGRESS
FROM EDUX.COURSE c
LEFT JOIN EDUX.ENROLLMENT e ON c.C_ID = e.C_ID
LEFT JOIN EDUX.COURSE_RATING r ON c.C_ID = r.C_ID
GROUP BY c.C_ID, c.NAME, c.I_ID;

COMMIT;
