-- Phase 5: Database Schema Extensions
-- New tables for certificates, discussions, live sessions, payments, gamification, and versioning

-- Ensure we are operating in the EDUX PDB (required for multi-PDB container setups)
ALTER SESSION SET CONTAINER = EDUX;


-- ================================================
-- CERTIFICATES TABLE
-- ================================================
CREATE TABLE EDUX.CERTIFICATES (
    CERT_ID VARCHAR2(50) PRIMARY KEY,
    U_ID NUMBER NOT NULL,
    C_ID NUMBER NOT NULL,
    ISSUED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERIFICATION_URL VARCHAR2(500),
    TEMPLATE VARCHAR2(50) DEFAULT 'STANDARD',
    CONSTRAINT FK_CERT_USER FOREIGN KEY (U_ID) REFERENCES EDUX."Users"("u_id"),
    CONSTRAINT FK_CERT_COURSE FOREIGN KEY (C_ID) REFERENCES EDUX."Courses"("c_id")
);

CREATE INDEX IDX_CERT_USER ON EDUX.CERTIFICATES(U_ID);
CREATE INDEX IDX_CERT_COURSE ON EDUX.CERTIFICATES(C_ID);

-- ================================================
-- DISCUSSIONS TABLE
-- ================================================
CREATE TABLE EDUX.DISCUSSIONS (
    THREAD_ID VARCHAR2(50) PRIMARY KEY,
    C_ID NUMBER NOT NULL,
    U_ID NUMBER NOT NULL,
    TITLE VARCHAR2(500) NOT NULL,
    CONTENT CLOB,
    IS_PINNED NUMBER(1) DEFAULT 0,
    IS_LOCKED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_DISC_COURSE FOREIGN KEY (C_ID) REFERENCES EDUX."Courses"("c_id"),
    CONSTRAINT FK_DISC_USER FOREIGN KEY (U_ID) REFERENCES EDUX."Users"("u_id")
);

CREATE TABLE EDUX.DISCUSSION_REPLIES (
    REPLY_ID VARCHAR2(50) PRIMARY KEY,
    THREAD_ID VARCHAR2(50) NOT NULL,
    U_ID NUMBER NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_REPLY_THREAD FOREIGN KEY (THREAD_ID) REFERENCES EDUX.DISCUSSIONS(THREAD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REPLY_USER FOREIGN KEY (U_ID) REFERENCES EDUX."Users"("u_id")
);

CREATE INDEX IDX_DISC_COURSE ON EDUX.DISCUSSIONS(C_ID);
CREATE INDEX IDX_DISC_USER ON EDUX.DISCUSSIONS(U_ID);
CREATE INDEX IDX_REPLY_THREAD ON EDUX.DISCUSSION_REPLIES(THREAD_ID);

-- ================================================
-- LIVE SESSIONS TABLES
-- ================================================
CREATE TABLE EDUX.LIVE_SESSIONS (
    SESSION_ID VARCHAR2(100) PRIMARY KEY,
    C_ID NUMBER NOT NULL,
    INSTRUCTOR_ID NUMBER NOT NULL,
    TITLE VARCHAR2(500) NOT NULL,
    DESCRIPTION CLOB,
    TYPE VARCHAR2(50) DEFAULT 'lecture',
    ROOM_NAME VARCHAR2(100),
    PASSWORD VARCHAR2(50),
    SCHEDULED_START TIMESTAMP NOT NULL,
    SCHEDULED_END TIMESTAMP,
    DURATION NUMBER DEFAULT 60,
    MAX_PARTICIPANTS NUMBER DEFAULT 100,
    STATUS VARCHAR2(20) DEFAULT 'scheduled',
    STARTED_AT TIMESTAMP,
    ENDED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SESSION_COURSE FOREIGN KEY (C_ID) REFERENCES EDUX."Courses"("c_id"),
    CONSTRAINT FK_SESSION_INSTRUCTOR FOREIGN KEY (INSTRUCTOR_ID) REFERENCES EDUX."Instructors"("i_id")
);

CREATE TABLE EDUX.SESSION_PARTICIPANTS (
    SESSION_ID VARCHAR2(100) NOT NULL,
    USER_ID NUMBER NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'participant',
    JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LEFT_AT TIMESTAMP,
    PRIMARY KEY (SESSION_ID, USER_ID),
    CONSTRAINT FK_PARTICIPANT_SESSION FOREIGN KEY (SESSION_ID) REFERENCES EDUX.LIVE_SESSIONS(SESSION_ID),
    CONSTRAINT FK_PARTICIPANT_USER FOREIGN KEY (USER_ID) REFERENCES EDUX."Users"("u_id")
);

CREATE INDEX IDX_SESSION_COURSE ON EDUX.LIVE_SESSIONS(C_ID);
CREATE INDEX IDX_SESSION_INSTRUCTOR ON EDUX.LIVE_SESSIONS(INSTRUCTOR_ID);
CREATE INDEX IDX_SESSION_STATUS ON EDUX.LIVE_SESSIONS(STATUS);

-- ================================================
-- PAYMENTS TABLE
-- ================================================
CREATE TABLE EDUX.PAYMENTS (
    PAYMENT_ID VARCHAR2(50) PRIMARY KEY,
    U_ID NUMBER NOT NULL,
    C_ID NUMBER NOT NULL,
    AMOUNT NUMBER(10,2) NOT NULL,
    CURRENCY VARCHAR2(3) DEFAULT 'USD',
    STATUS VARCHAR2(20) DEFAULT 'pending',
    STRIPE_SESSION_ID VARCHAR2(200),
    COUPON_CODE VARCHAR2(50),
    REFUND_REASON VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    REFUNDED_AT TIMESTAMP,
    CONSTRAINT FK_PAYMENT_USER FOREIGN KEY (U_ID) REFERENCES EDUX."Users"("u_id"),
    CONSTRAINT FK_PAYMENT_COURSE FOREIGN KEY (C_ID) REFERENCES EDUX."Courses"("c_id")
);

CREATE INDEX IDX_PAYMENT_USER ON EDUX.PAYMENTS(U_ID);
CREATE INDEX IDX_PAYMENT_COURSE ON EDUX.PAYMENTS(C_ID);
CREATE INDEX IDX_PAYMENT_STATUS ON EDUX.PAYMENTS(STATUS);
CREATE INDEX IDX_PAYMENT_STRIPE ON EDUX.PAYMENTS(STRIPE_SESSION_ID);

-- ================================================
-- GAMIFICATION TABLES
-- ================================================
CREATE TABLE EDUX.USER_XP (
    XP_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    U_ID NUMBER NOT NULL,
    XP_AMOUNT NUMBER NOT NULL,
    ACTION VARCHAR2(100),
    C_ID NUMBER,
    EARNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_XP_USER FOREIGN KEY (U_ID) REFERENCES EDUX."Users"("u_id"),
    CONSTRAINT FK_XP_COURSE FOREIGN KEY (C_ID) REFERENCES EDUX."Courses"("c_id")
);

CREATE TABLE EDUX.USER_BADGES (
    U_ID NUMBER NOT NULL,
    BADGE_ID VARCHAR2(50) NOT NULL,
    EARNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (U_ID, BADGE_ID),
    CONSTRAINT FK_BADGE_USER FOREIGN KEY (U_ID) REFERENCES EDUX."Users"("u_id")
);

CREATE TABLE EDUX.USER_ACTIVITY (
    ACTIVITY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    U_ID NUMBER NOT NULL,
    ACTIVITY_TYPE VARCHAR2(50),
    ACTIVITY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACTIVITY_USER FOREIGN KEY (U_ID) REFERENCES EDUX."Users"("u_id")
);

CREATE TABLE EDUX.USER_STREAKS (
    U_ID NUMBER PRIMARY KEY,
    CURRENT_STREAK NUMBER DEFAULT 0,
    LONGEST_STREAK NUMBER DEFAULT 0,
    LAST_ACTIVITY_DATE DATE,
    CONSTRAINT FK_STREAK_USER FOREIGN KEY (U_ID) REFERENCES EDUX."Users"("u_id")
);

CREATE INDEX IDX_XP_USER ON EDUX.USER_XP(U_ID);
CREATE INDEX IDX_XP_ACTION ON EDUX.USER_XP(ACTION);
CREATE INDEX IDX_ACTIVITY_USER ON EDUX.USER_ACTIVITY(U_ID);
CREATE INDEX IDX_ACTIVITY_DATE ON EDUX.USER_ACTIVITY(ACTIVITY_DATE);

-- ================================================
-- CONTENT VERSIONING TABLE
-- ================================================
CREATE TABLE EDUX.CONTENT_VERSIONS (
    VERSION_ID VARCHAR2(100) PRIMARY KEY,
    CONTENT_TYPE VARCHAR2(50) NOT NULL,
    CONTENT_ID VARCHAR2(50) NOT NULL,
    COURSE_ID NUMBER,
    ACTION VARCHAR2(20) NOT NULL,
    USER_ID NUMBER,
    PREVIOUS_DATA CLOB,
    NEW_DATA CLOB,
    MESSAGE VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_VERSION_USER FOREIGN KEY (USER_ID) REFERENCES EDUX."Users"("u_id"),
    CONSTRAINT FK_VERSION_COURSE FOREIGN KEY (COURSE_ID) REFERENCES EDUX."Courses"("c_id")
);

CREATE INDEX IDX_VERSION_CONTENT ON EDUX.CONTENT_VERSIONS(CONTENT_TYPE, CONTENT_ID);
CREATE INDEX IDX_VERSION_COURSE ON EDUX.CONTENT_VERSIONS(COURSE_ID);
CREATE INDEX IDX_VERSION_DATE ON EDUX.CONTENT_VERSIONS(CREATED_AT);

-- ================================================
-- ADD COLUMNS TO EXISTING TABLES
-- ================================================

-- Add COMPLETED and COMPLETED_AT columns to existing ENROLLS table (this project uses "Enrolls")
ALTER TABLE EDUX."Enrolls" ADD (
    COMPLETED NUMBER(1) DEFAULT 0,
    COMPLETED_AT TIMESTAMP
);

-- Add PRICE column to Courses
ALTER TABLE EDUX."Courses" ADD (
    PRICE NUMBER(10,2) DEFAULT 0
);

-- ================================================
-- VIEWS FOR ANALYTICS
-- ================================================

-- Leaderboard View
CREATE OR REPLACE VIEW EDUX.V_LEADERBOARD AS
SELECT 
    u."u_id" AS U_ID,
    u."name" AS NAME,
    NVL(SUM(x.XP_AMOUNT), 0) as TOTAL_XP,
    (SELECT COUNT(*) FROM EDUX.USER_BADGES b WHERE b.U_ID = u."u_id") as BADGE_COUNT,
    RANK() OVER (ORDER BY NVL(SUM(x.XP_AMOUNT), 0) DESC) as RANK
FROM EDUX."Users" u
LEFT JOIN EDUX.USER_XP x ON u."u_id" = x.U_ID
GROUP BY u."u_id", u."name";

-- Instructor Analytics View
CREATE OR REPLACE VIEW EDUX.V_INSTRUCTOR_STATS AS
SELECT 
    u."u_id" AS I_ID,
    u."name" as INSTRUCTOR_NAME,
    COUNT(DISTINCT c."c_id") as TOTAL_COURSES,
    COUNT(DISTINCT e."s_id") as TOTAL_STUDENTS,
    NVL(AVG(f."rating"), 0) as AVG_RATING,
    COUNT(DISTINCT f."s_id") as TOTAL_REVIEWS,
    NVL(SUM(p.AMOUNT), 0) as TOTAL_REVENUE
FROM EDUX."Instructors" ins
LEFT JOIN EDUX."Users" u ON ins."i_id" = u."u_id"
LEFT JOIN EDUX."Courses" c ON ins."i_id" = c."i_id"
LEFT JOIN EDUX."Enrolls" e ON c."c_id" = e."c_id"
LEFT JOIN EDUX."Feedbacks" f ON c."c_id" = f."c_id"
LEFT JOIN EDUX.PAYMENTS p ON c."c_id" = p.C_ID AND p.STATUS = 'completed'
GROUP BY u."u_id", u."name";

-- Course Performance View
CREATE OR REPLACE VIEW EDUX.V_COURSE_PERFORMANCE AS
SELECT 
    c."c_id" AS C_ID,
    c."title" as COURSE_NAME,
    c."i_id" as INSTRUCTOR_ID,
    COUNT(DISTINCT e."s_id") as ENROLLMENT_COUNT,
    NVL(AVG(f."rating"), 0) as AVG_RATING,
    COUNT(CASE WHEN e.COMPLETED = 1 THEN 1 END) as COMPLETIONS,
    NVL(AVG(e."progress"), 0) as AVG_PROGRESS
FROM EDUX."Courses" c
LEFT JOIN EDUX."Enrolls" e ON c."c_id" = e."c_id"
LEFT JOIN EDUX."Feedbacks" f ON c."c_id" = f."c_id"
GROUP BY c."c_id", c."title", c."i_id";

COMMIT;
