-- Phase 6: Retrieval-Augmented Generation (grounded AI course tutor)
-- Tables for lecture transcripts and the embedded retrieval corpus.
-- For an existing database, run this file manually once (it only creates
-- new objects; it does not touch existing tables).

-- Ensure we are operating in the EDUX PDB (required for multi-PDB container setups)
ALTER SESSION SET CONTAINER = EDUX;


-- ================================================
-- LECTURE TRANSCRIPTS
-- Full text attached to a lecture (transcript, notes, or reading material).
-- This is the primary grounding corpus for the AI tutor.
-- ================================================
CREATE TABLE EDUX.LECTURE_TRANSCRIPTS (
    L_ID NUMBER PRIMARY KEY,
    CONTENT CLOB NOT NULL,
    LANGUAGE VARCHAR2(10) DEFAULT 'en',
    SOURCE VARCHAR2(30) DEFAULT 'manual', -- manual | imported | auto
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TRANSCRIPT_LECTURE FOREIGN KEY (L_ID)
        REFERENCES EDUX."Lectures"("l_id") ON DELETE CASCADE
);

-- ================================================
-- RAG CHUNKS
-- The embedded retrieval corpus. One row per chunk of course content.
-- EMBEDDING holds little-endian float32 values (4 bytes per dimension);
-- EMBEDDING_MODEL records which provider/model produced the vector so
-- vectors from different models are never compared to each other.
-- CONTENT_HASH (SHA-256 hex) makes re-ingestion idempotent: unchanged
-- chunks keep their embedding instead of being re-embedded.
-- ================================================
CREATE TABLE EDUX.RAG_CHUNKS (
    CHUNK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    C_ID NUMBER NOT NULL,
    T_ID NUMBER,
    L_ID NUMBER,
    SOURCE_TYPE VARCHAR2(20) NOT NULL, -- overview | syllabus | lecture
    TITLE VARCHAR2(300) NOT NULL,
    CONTENT CLOB NOT NULL,
    CONTENT_HASH VARCHAR2(64) NOT NULL,
    SEQ NUMBER DEFAULT 0,
    EMBEDDING BLOB,
    EMBEDDING_MODEL VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_RAGCHUNK_COURSE FOREIGN KEY (C_ID)
        REFERENCES EDUX."Courses"("c_id") ON DELETE CASCADE,
    CONSTRAINT FK_RAGCHUNK_TOPIC FOREIGN KEY (T_ID)
        REFERENCES EDUX."Topics"("t_id") ON DELETE CASCADE,
    CONSTRAINT FK_RAGCHUNK_LECTURE FOREIGN KEY (L_ID)
        REFERENCES EDUX."Lectures"("l_id") ON DELETE CASCADE
);

CREATE INDEX IDX_RAGCHUNK_COURSE ON EDUX.RAG_CHUNKS(C_ID);
CREATE INDEX IDX_RAGCHUNK_HASH ON EDUX.RAG_CHUNKS(C_ID, CONTENT_HASH);


-- ================================================
-- SAMPLE TRANSCRIPTS
-- Lecture notes for the seeded demo courses so the AI tutor has real
-- content to ground on out of the box. Written for this project.
-- ================================================

INSERT INTO EDUX.LECTURE_TRANSCRIPTS (L_ID, CONTENT, SOURCE) VALUES (2000,
'React is a JavaScript library for building user interfaces, created and maintained by Meta. The core idea behind React is that a user interface should be a function of application state: instead of manually finding and updating parts of the page, you describe what the UI should look like for a given state, and React updates the browser DOM to match.

React achieves this efficiently through the virtual DOM. The virtual DOM is a lightweight in-memory representation of the real DOM. When state changes, React builds a new virtual DOM tree, compares it with the previous one using a diffing algorithm called reconciliation, and applies only the minimal set of changes to the real DOM. Direct DOM manipulation is slow; reconciliation keeps updates fast even in large applications.

Why choose React over plain JavaScript? Three main reasons. First, its component model lets you split a complex interface into small, reusable, testable pieces. Second, declarative rendering removes an entire class of bugs that come from imperative DOM code getting out of sync with data. Third, React has a massive ecosystem: routing, state management, testing tools, and frameworks such as Next.js are built on top of it.

React is a library rather than a full framework: it handles rendering, and you compose it with other tools for routing, data fetching, and builds. This flexibility is one reason it remains the most widely used UI library in industry.', 'manual');

INSERT INTO EDUX.LECTURE_TRANSCRIPTS (L_ID, CONTENT, SOURCE) VALUES (2001,
'Before writing React code you need a development toolchain. Modern React development relies on three pieces: a package manager (npm, yarn, or pnpm) to install dependencies, a bundler to combine your modules into files the browser can load, and a dev server with hot module replacement so changes appear instantly without a full reload.

For years the standard starting point was Create React App (CRA), which hid webpack and Babel configuration behind a single command. CRA is now deprecated and no longer recommended for new projects. The community default today is Vite. Vite starts a dev server in milliseconds because it serves source files over native ES modules and only bundles for production, using esbuild for dependency pre-bundling and Rollup for production builds.

To scaffold a project with Vite you run: npm create vite@latest my-app, choose the React template, then npm install and npm run dev. The dev server runs on port 5173 by default. The project structure includes an index.html entry point, a src folder with main.jsx that mounts your root component into the DOM with createRoot, and an App.jsx root component.

JSX is the syntax extension that lets you write HTML-like markup inside JavaScript. Browsers cannot execute JSX directly, so the toolchain compiles it to React.createElement calls (or the newer automatic JSX runtime) during the build step. Understanding that JSX is just JavaScript after compilation explains most of its rules, such as using className instead of class and wrapping sibling elements in a single parent.', 'manual');

INSERT INTO EDUX.LECTURE_TRANSCRIPTS (L_ID, CONTENT, SOURCE) VALUES (2002,
'A functional component is a JavaScript function that returns JSX describing part of the user interface. Since the introduction of hooks in React 16.8, functional components are the standard way to write React code; class components still work but are legacy in new codebases.

A component function must start with a capital letter — that is how JSX distinguishes your components from built-in HTML elements like div or button. A minimal component looks like: function Welcome() { return <h1>Hello!</h1>; } and is used as <Welcome /> inside other components.

Components compose: a page is a tree of components, each responsible for one piece of UI. A ProductPage might render a Header, a ProductGallery, and a ReviewList, and ReviewList in turn renders many Review components. This decomposition is the main design activity in React: identify the pieces of your interface, decide their boundaries, and keep each component focused on one job.

Rendering rules to remember: a component must return a single root element (use a Fragment, written <>...</>, when you do not want an extra wrapper node); expressions inside JSX go in curly braces; and rendering must be pure — a component should not modify variables outside itself or trigger side effects during render. Side effects belong in event handlers or in the useEffect hook, which runs after rendering.

When a list of elements is rendered with map, each element needs a stable key prop so React can match items between renders during reconciliation. Using array indexes as keys causes subtle bugs when the list is reordered or filtered.', 'manual');

INSERT INTO EDUX.LECTURE_TRANSCRIPTS (L_ID, CONTENT, SOURCE) VALUES (2003,
'Props (short for properties) are how data flows from a parent component to its children. Props are passed like HTML attributes and received as the component''s single argument, conventionally destructured: function Avatar({ user, size }) { ... } used as <Avatar user={currentUser} size={64} />.

Two rules define props. First, props are read-only: a component must never modify the props it receives. If a child needs to change data, the parent passes down a callback function as a prop and the child calls it — this is called lifting state up, and it keeps data flowing in one direction, from parent to child. Unidirectional data flow is what makes React applications predictable and debuggable: to find why a value is wrong, you walk up the tree to whoever owns the state.

Second, any JavaScript value can be a prop: strings, numbers, objects, arrays, functions, and even other React elements. Passing elements as props enables the composition pattern. The special children prop holds whatever you nest between a component''s opening and closing tags, so <Card><ProfileInfo /></Card> lets Card render a styled frame around arbitrary content without knowing what that content is.

Composition is preferred over inheritance in React. Instead of subclassing a Button to make an IconButton, you write an IconButton component that renders a Button and passes different props. Specialization through props and children covers every case class inheritance would, with far less coupling. The React team explicitly recommends against component inheritance hierarchies.', 'manual');

INSERT INTO EDUX.LECTURE_TRANSCRIPTS (L_ID, CONTENT, SOURCE) VALUES (2004,
'State is data that changes over time and belongs to a specific component. The useState hook declares a piece of state: const [count, setCount] = useState(0); returns the current value and a setter function. Calling the setter re-renders the component with the new value. State is preserved between renders — unlike ordinary variables, which are reinitialized every render.

Three rules govern useState. Call hooks only at the top level of a component, never inside conditions or loops, because React tracks hooks by call order. Never mutate state directly — create a new object or array and pass it to the setter, since React detects changes by reference comparison. And when the next state depends on the previous one, pass an updater function: setCount(c => c + 1), which avoids stale-value bugs when updates are batched.

The useEffect hook handles side effects: work that reaches outside rendering, such as fetching data, subscribing to a WebSocket, or setting document.title. useEffect takes a function and a dependency array. The effect runs after render, and re-runs only when a dependency changes. An empty array means run once after the initial mount. The function may return a cleanup function, which React calls before the next effect run and when the component unmounts — that is where you unsubscribe, clear timers, or abort fetches to prevent memory leaks.

A common mistake is overusing useEffect. If a value can be computed from existing props and state, compute it during render instead of storing it in state and syncing with an effect. Effects are for synchronizing with external systems, not for transforming data you already have.', 'manual');

INSERT INTO EDUX.LECTURE_TRANSCRIPTS (L_ID, CONTENT, SOURCE) VALUES (2010,
'Node.js is a JavaScript runtime built on Chrome''s V8 engine that runs JavaScript outside the browser, on servers and developer machines. Its defining characteristic is an event-driven, non-blocking I/O model: instead of dedicating a thread to each connection, Node runs a single-threaded event loop that starts I/O operations (file reads, network requests, database queries) and continues processing other work while the operating system completes them. This makes Node exceptionally good at I/O-heavy workloads such as APIs and real-time services, though CPU-heavy work must be offloaded to worker threads or separate processes to avoid blocking the loop.

Core modules ship with the runtime and need no installation. The fs module reads and writes files (prefer the promise-based fs/promises API). The path module joins and normalizes file paths across operating systems. The http module creates web servers and clients, and is the foundation frameworks like Express build on. The os module reports system information, and crypto provides hashing and encryption primitives.

Modules are loaded with require() in CommonJS or import in ES modules; package.json declares dependencies and scripts, and npm installs them into node_modules. The event loop plus callback queue explains Node concurrency: synchronous code runs first, then microtasks (resolved promises), then timers and I/O callbacks. Understanding that ordering is the key to reasoning about async behavior in any Node program.', 'manual');

INSERT INTO EDUX.LECTURE_TRANSCRIPTS (L_ID, CONTENT, SOURCE) VALUES (2011,
'Express is the most widely used web framework for Node.js. It wraps the raw http module with two ideas: routing and middleware. A route maps an HTTP method and URL pattern to a handler function: app.get(''/courses/:id'', (req, res) => { ... }). Route parameters like :id appear on req.params; query strings on req.query; and parsed request bodies on req.body once body-parsing middleware is enabled with app.use(express.json()).

Middleware are functions with the signature (req, res, next) that run in order for every matching request before the final handler. Each middleware can inspect or modify the request and response, end the cycle by sending a response, or call next() to pass control onward. Authentication checks, logging, CORS headers, rate limiting, and body parsing are all middleware. This pipeline architecture is Express''s core design: a request flows through a chain of small functions, each with one responsibility.

Error handling uses a special four-argument middleware signature (err, req, res, next). Throwing inside an async handler does not reach it automatically in Express 4 — you must call next(err) or wrap handlers — which is one of the most common Express bugs.

A well-structured Express API groups routes with express.Router, keeps handlers thin by delegating to service functions, validates input at the boundary, and returns consistent JSON shapes with correct status codes: 200 for success, 201 for creation, 400 for invalid input, 401 for missing authentication, 403 for insufficient permissions, 404 for missing resources, and 500 for unexpected server errors.', 'manual');

INSERT INTO EDUX.LECTURE_TRANSCRIPTS (L_ID, CONTENT, SOURCE) VALUES (2020,
'Python is a dynamically typed, interpreted language whose readable syntax makes it the standard choice for data science. This lecture covers the type system and control flow you need before touching data libraries.

Python''s core built-in types: int and float for numbers (integers have arbitrary precision), str for immutable Unicode text, bool for True and False, and None for the absence of a value. The workhorse collections are list (ordered, mutable), tuple (ordered, immutable), dict (key-value mapping, insertion-ordered), and set (unordered unique elements). Choosing the right collection matters: membership tests are O(1) for sets and dicts but O(n) for lists.

Control flow uses indentation rather than braces. if/elif/else handles branching; for iterates over any iterable (not just numeric ranges); while loops until a condition fails; break and continue adjust loop execution. The enumerate function gives you index and value together, and zip iterates several sequences in parallel.

List comprehensions are the idiomatic way to transform collections: squares = [x**2 for x in range(10) if x % 2 == 0] builds a list in one readable expression, replacing a four-line loop. Dict and set comprehensions work the same way.

Functions are defined with def, support default and keyword arguments, and are first-class values you can pass around. Errors are handled with try/except blocks; catching specific exception types rather than bare except is essential practice. These fundamentals — collections, comprehensions, and functions — are exactly the constructs pandas builds on.', 'manual');

INSERT INTO EDUX.LECTURE_TRANSCRIPTS (L_ID, CONTENT, SOURCE) VALUES (2021,
'Pandas is the standard Python library for tabular data analysis. It provides two core data structures. A Series is a one-dimensional labeled array: values plus an index. A DataFrame is a two-dimensional table of rows and columns — conceptually a dict of Series sharing the same row index. Nearly all data work in pandas is manipulating DataFrames.

You typically create a DataFrame by reading a file: pd.read_csv(''sales.csv'') infers column types and returns a DataFrame. First-look methods: df.head() shows the first rows, df.info() summarizes columns, types, and missing values, and df.describe() gives summary statistics for numeric columns.

Selection has two labeled accessors. df.loc selects by label: df.loc[5, ''price''] is the price column of the row labeled 5, and df.loc[df[''price''] > 100] filters rows with a boolean mask. df.iloc selects by integer position regardless of labels. Boolean masking is the idiomatic way to filter: combine conditions with & and | and wrap each condition in parentheses.

Missing data appears as NaN. df.isna().sum() counts missing values per column; df.dropna() removes incomplete rows; df.fillna(value) imputes them. Deciding between dropping and imputing is an analytical judgment, not a mechanical step.

The most powerful pattern is split-apply-combine with groupby: df.groupby(''region'')[''revenue''].sum() splits rows by region, sums revenue within each group, and combines the results into a new Series. Grouped aggregation, joined with merge (SQL-style joins between DataFrames), covers the majority of real-world analysis tasks.', 'manual');

COMMIT;
